name: Deploy Next.js + Prisma

on:
  push:
    branches: [main]

env:
  APP_DIR: /home/akfrgser/duka
  HOST: node241-eu.n0c.com
  USER: akfrgser

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Build Next.js app (standalone)
        run: |
          npm run build
          mkdir -p output
          cp -r .next/standalone output/
          cp -r .next/static output/
          cp -r public output/
          cp server.js output/
          cp package.json output/

      - name: Prepare SSH connection
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Upload build to server
        run: |
          rsync -avz --delete output/ $USER@$HOST:$APP_DIR

      - name: Deploy and run Prisma migration
        run: |
          ssh $USER@$HOST << 'EOF'
          cd $APP_DIR
          source /home/akfrgser/nodevenv/duka/20/bin/activate
          export DATABASE_URL="${{ secrets.DATABASE_URL }}"
          npm install --omit=dev
          npx prisma migrate deploy
          passenger-config restart-app $APP_DIR
          EOF
